name: sync_tree_modile_ui
description: mobile application for access to sync_tree crypto token.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI dependencies
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  modal_bottom_sheet: ^2.0.0
  top_snackbar_flutter: ^1.0.0
  animations: ^2.0.1
  # ANOTHER dependencies
  pointycastle: ^3.1.1
  basic_utils: ^3.1.0
  clipboard: ^0.1.3
  fixnum: ^1.0.0
  protobuf: ^2.0.0
  grpc: ^3.0.0
  shared_preferences: ^2.0.5

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.3

flutter:
  uses-material-design: true
