name: sync_tree_mobile
description: A flutter application for sync_tree token

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bad_words: ^0.2.2
  shared_preferences: ^2.0.5
  ffi: ^1.0.0
  flutter:
    sdk: flutter
  animations: ^2.0.0
  image_picker: ^0.8.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true