name: sync_tree_mobile
description: A flutter application for sync_tree token

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  crypto_export:
    path: /Users/danilafominyh/Documents/crypto_export
  bad_words: ^0.2.2
  shared_preferences: ^2.0.5
  flutter_spinkit: ^5.0.0
  clipboard: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true